### PR TITLE
Fix initial props handling

### LINKED ISSUE #20: MDX => Slate drops props in JSX blocks

### PR DESCRIPTION
**Pull request by johno**
When initialized, the props passed for serialization are
an immutable js map but all subsequent props values are
standard js objects. To keep things simple let's ensure
all maps are coerced into vanilla js objects.

Fixes #20

### CODE REVIEW

File: packages/serializer/src/util.js [hunk 1]
```diff
@@ -6,3 +6,8 @@ export const getComponentName = (str = '') => {
   const match = str.match(/^\<?([\w\.\_]+)/)
   return match && match[1]
 }
+
+export const toJS = map => {
+  if (typeof map.toJS !== 'function') return map
+  return map.toJS()
```
Comment (jxnblk) [inline packages/serializer/src/util.js]: Would this negate the need for the `getProps` thing I'm doing in the node rendering?

Comment (johno) [reply packages/serializer/src/util.js]: It won't unfortunately, this is coming back from Slate schema before `getProps` is run in the editor.
